# .streamlit/secrets.toml

# Databricks SQL Endpoint connection details
[databricks]
server_hostname = "dbc-5efd037f-10fd.cloud.databricks.com"
http_path = "/sql/1.0/warehouses/6702eda7b17a3c0b"
access_token = "dapi8d906e4332743ebeadaa3696effabdf2"

# Example of a table name you might want to query
# You can have multiple tables listed or use a variable in your app.py
table_name = "test.edu_loan.applications"